#!/bin/bash

# check that some arguments were passed...
if [[ $# -eq 0 ]]
then
  echo "ERROR: arguments required, use option -h or --help for help" 1>&2
  echo "Exiting"
  exit 1
fi

# process arguments
while [[ $# -gt 0 ]]
do
        key="$1"
        case $key in
                -h|--help )
                        echo "Usage:"
                        echo "-p or --partition Partition to use for interactive session eg -p smew01 will start a job on partition smew01-debug."
                        echo "-h or --help Display this help message."
                        echo "Exiting."
                        exit 0
                        ;;
                -p|--partition )
                        partitionname=$2
                        echo "partition specified as $partitionname"
                        shift 
                        shift
                        ;;
                *)
                        echo "ERROR: Unknown argument ${key} entered, exiting"
                        echo "use option -h or --help to see valid options."
                        exit 1
        esac
done

# check if this is a slurm head node
sinfo &> /dev/null 
if [[ $? -ne 0 ]]
then
        echo "sinfo exited with non-zero exit status: this is probably not a slurm head node"
        echo "check you are logged into a slurm head node"
        echo "EXITING"
        exit 1
fi

# append -debug to partition name if missing.

tmp=$(echo ${partitionname} | grep "\-debug" | wc -l)
if [[ $tmp -eq 0 ]]
then
    echo '"-debug" not detected in partition name, appending to end'
    PART="${partitionname}-debug"
else
    PART=${partitionname}
fi

#echo "Specifying partition : ${PART}"
# if partition is named correctly, try to start 30 minute debug session.
tmp=$(sinfo | cut -d" " -f1 | grep ${PART} | wc -l)
if [[ $tmp -gt 0 ]]
then
    CMD="srun --pty -t 0:30:00 --partition=${PART} --chdir /data/localhost/not-backed-up/${USER}/ bash"
else
    echo "${PART} is not an available partition, run sinfo to view partition status"
    exit 1
fi
echo "Running command: ${CMD}"
$CMD
